### PR TITLE
troll timer

### PR DESCRIPTION
**Pull request by MadMub**
200w

### CODE REVIEW

**Comment by epixa** [comment]
This kind of seems like a violation of rule 12...

> Players must be in the spirit of the game and must not intentionally make the next player's turn more difficult.

@patvice @celsodantas @kurtfunai @uri Verdict?

**Comment by MadMub** [comment]
So far it's something that will happen in 0-42 seconds. I haven't killed the process...yet

**Comment by kurtfunai** [comment]
It does seem a little evil :P

**Comment by MadMub** [comment]
Lol it's a timeout that doesn't do anything yet. I would be stoked if someone set me up with something fun and open ended like that...

**Comment by celsodantas** [comment]
yeah, it looks evil. Even his commit message is evil and the gif is evil. Dude, he is all evil.

**Comment by epixa** [comment]
For the record, it's the randomness of the timeout that red flagged it for me.

**Pull request merged**
