### PR TITLE
Uri joins the battle

### PR DESCRIPTION
**Pull request by uri**

### CODE REVIEW

**Comment by epixa** [comment]
@uri Can you put yourself in alphabetical order by last name?

**Comment by uri** [comment]
Shame on me, missed rule 15. Will do right away.

**Comment by epixa** [comment]
Did you push a new commit that didn't actually move yourself anywhere or is github's caching messed up?

**Comment by uri** [comment]
Yeah I believe the PR diff is out of date. Should be able to get it displaying correctly by opening a new PR.

**Pull request closed without merging**
